name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

# Sanitizers and warnings as errors are enabled automatically
env:
  CI: true

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-arm, macos-latest, macos-14]
        build_type: [Release, Debug]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # We could just run make test here but this will give us nicer info at a glance
      - name: Configure
        run: make configure CMAKE_FLAGS=-DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Build
        run: make build CMAKE_FLAGS=-DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Test
        run: make test CMAKE_FLAGS=-DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
